// Helper function to generate exercise data with descriptions
function getDefaultExercisesWithDescriptions() {
    return [
        ['Exercise Name', 'Default Weight', 'Default Reps', 'Default Time (seconds)', 'Description'],
        ['# Add # at start of exercise name to hide it from dropdown', '', '', '', ''],
        ['', '', '', '', ''],
        ['# === AB EXERCISES ===', '', '', '', ''],
        ['Stomach Vacuum', '0', '0', '30', 'Exhale all air, pull belly button toward spine, hold. Great for transverse abdominis.'],
        ['Plank', '0', '0', '60', 'Forearms on ground, body straight from head to heels. Engage core, don\'t let hips sag.'],
        ['Side Plank (Left)', '0', '0', '30', 'On left forearm, stack feet, lift hips. Keep body in straight line.'],
        ['Side Plank (Right)', '0', '0', '30', 'On right forearm, stack feet, lift hips. Keep body in straight line.'],
        ['Hollow Body Hold', '0', '0', '30', 'Lie on back, press lower back to floor, lift shoulders and legs. Arms overhead.'],
        ['Dead Bug', '0', '20', '0', 'On back, extend opposite arm and leg while keeping core engaged. Alternate sides.'],
        ['Bicycle Crunches', '0', '30', '0', 'On back, bring opposite elbow to knee in cycling motion. Keep core tight.'],
        ['Russian Twists', '0', '30', '0', 'Seated, lean back, twist torso side to side. Can hold weight for resistance.'],
        ['Leg Raises', '0', '15', '0', 'Lie on back, lift straight legs to 90°, lower slowly without touching ground.'],
        ['Flutter Kicks', '0', '30', '0', 'On back, lift legs slightly, alternate small up-down kicks. Keep core engaged.'],
        ['Mountain Climbers', '0', '30', '0', 'Plank position, drive knees to chest alternating quickly. Keep hips level.'],
        ['V-Ups', '0', '15', '0', 'Lie flat, simultaneously lift legs and torso to form V shape. Touch toes.'],
        ['Situps', '0', '30', '0', 'Lie on back, knees bent, lift torso to knees. Control the descent.'],
        ['', '', '', '', ''],
        ['# === PULL-UP BAR EXERCISES ===', '', '', '', ''],
        ['Pullups', '0', '10', '0', 'Hang from bar, pull chin over bar. Full range of motion, control descent.'],
        ['Chin-ups', '0', '10', '0', 'Like pullups but palms facing you. Easier variation, works biceps more.'],
        ['Negative Pullups', '0', '5', '0', 'Jump to top position, lower yourself slowly (5+ seconds).'],
        ['Dead Hang', '0', '0', '30', 'Hang from bar with straight arms. Builds grip strength and decompresses spine.'],
        ['Hanging Knee Raises', '0', '15', '0', 'Hang from bar, bring knees to chest. Control the movement.'],
        ['Hanging Leg Raises', '0', '10', '0', 'Hang from bar, lift straight legs to 90°. Advanced core exercise.'],
        ['L-Sit Hold', '0', '0', '20', 'Hang or support on bars, lift legs to 90° and hold. Very challenging.'],
        ['', '', '', '', ''],
        ['# === BODYWEIGHT/MAT EXERCISES ===', '', '', '', ''],
        ['Push-ups', '0', '20', '0', 'Hands shoulder-width, lower chest to ground, push up. Keep body straight.'],
        ['Diamond Push-ups', '0', '15', '0', 'Hands together forming diamond, targets triceps more than regular pushups.'],
        ['Wide Push-ups', '0', '15', '0', 'Hands wider than shoulders, emphasizes chest muscles.'],
        ['Pike Push-ups', '0', '12', '0', 'Hips high, head toward ground. Targets shoulders, progression to handstand pushups.'],
        ['Burpees', '0', '15', '0', 'Squat, jump back to plank, pushup, jump feet forward, jump up. Full body cardio.'],
        ['Squats', '0', '30', '0', 'Feet shoulder-width, lower hips back and down, keep chest up. Thighs parallel to ground.'],
        ['Jump Squats', '0', '20', '0', 'Regular squat but explode up into a jump. Land softly.'],
        ['Lunges', '0', '20', '0', 'Step forward, lower back knee toward ground. Keep front knee over ankle.'],
        ['Bulgarian Split Squats', '0', '15', '0', 'Back foot elevated, lunge down on front leg. Very challenging.'],
        ['Glute Bridges', '0', '25', '0', 'On back, knees bent, lift hips high. Squeeze glutes at top.'],
        ['Single Leg Glute Bridge', '0', '15', '0', 'Like glute bridge but one leg extended. Harder balance and strength.'],
        ['Wall Sit', '0', '0', '60', 'Back against wall, slide down to 90° knee angle. Hold position.'],
        ['Calf Raises', '0', '30', '0', 'Rise up on toes, lower slowly. Can do on edge of step for more range.'],
        ['', '', '', '', ''],
        ['# === DUMBBELL EXERCISES ===', '', '', '', ''],
        ['Dumbbell Curl', '20', '12', '0', 'Arms at sides, curl weights to shoulders. Keep elbows stationary.'],
        ['Hammer Curl', '20', '12', '0', 'Like curls but palms facing each other. Works brachialis muscle.'],
        ['Overhead Press', '20', '12', '0', 'Start at shoulders, press weights overhead. Keep core tight.'],
        ['Lateral Raise', '15', '15', '0', 'Arms at sides, lift weights out to sides to shoulder height.'],
        ['Front Raise', '15', '12', '0', 'Arms at sides, lift weights forward to shoulder height.'],
        ['Bent Over Row', '25', '12', '0', 'Hinge at hips, pull weights to ribcage. Squeeze shoulder blades.'],
        ['Single Arm Row', '25', '12', '0', 'One hand supported, row weight with other arm. Alternate sides.'],
        ['Chest Press (Floor)', '25', '15', '0', 'Lie on floor, press weights up from chest. Good for home workouts.'],
        ['Chest Fly (Floor)', '20', '15', '0', 'Lie on floor, arc weights out and together. Stretch and squeeze chest.'],
        ['Goblet Squat', '30', '15', '0', 'Hold weight at chest, squat down. Great for form and depth.'],
        ['Dumbbell Deadlift', '40', '12', '0', 'Weights at sides, hinge at hips, lower weights along legs. Keep back straight.'],
        ['Dumbbell Lunge', '20', '20', '0', 'Hold weights at sides, perform lunges. Adds resistance to bodyweight movement.'],
        ['Dumbbell Shrug', '30', '15', '0', 'Weights at sides, lift shoulders toward ears. Targets traps.'],
        ['Tricep Extension', '20', '15', '0', 'Weight overhead, lower behind head, extend back up. Keep elbows still.'],
        ['Dumbbell Swing', '25', '20', '0', 'Hinge and swing weight between legs, thrust hips to swing up. Explosive movement.'],
        ['', '', '', '', ''],
        ['# === ISOMETRIC HOLDS ===', '', '', '', ''],
        ['Wall Sit', '0', '0', '60', 'Back against wall, slide down to 90° knee angle. Hold position.'],
        ['Plank', '0', '0', '60', 'Forearms on ground, body straight from head to heels. Engage core, don\'t let hips sag.'],
        ['Side Plank', '0', '0', '30', 'On forearm, stack feet, lift hips. Keep body in straight line.'],
        ['Hollow Body Hold', '0', '0', '30', 'Lie on back, press lower back to floor, lift shoulders and legs. Arms overhead.'],
        ['Superman Hold', '0', '0', '30', 'Lie face down, lift arms and legs off ground. Hold position.'],
        ['Bridge Hold', '0', '0', '45', 'Glute bridge position held at top. Squeeze glutes throughout.'],
        ['Dead Hang', '0', '0', '30', 'Hang from bar with straight arms. Builds grip strength and decompresses spine.'],
        ['L-Sit Hold', '0', '0', '20', 'Hang or support on bars, lift legs to 90° and hold. Very challenging.'],
        ['', '', '', '', ''],
        ['# === SEATED ISOMETRIC EXERCISES ===', '', '', '', ''],
        ['Seated Soleus Raise', '0', '30', '0', 'Seated, knees bent, raise heels off ground. Targets soleus muscle specifically.'],
        ['Seated Soleus Hold', '0', '0', '30', 'Seated calf raise held at top position. Burns the soleus.'],
        ['Seated Calf Raise', '0', '30', '0', 'Seated, raise heels up and down. Can add weight on knees.'],
        ['Seated Knee Extension Hold', '0', '0', '30', 'Seated, extend one leg straight and hold. Isometric quad work.'],
        ['Seated Hip Flexor Hold', '0', '0', '30', 'Seated, lift knee up and hold. Works hip flexors isometrically.'],
        ['Seated Glute Squeeze', '0', '20', '0', 'Seated, squeeze glutes hard. Can do anywhere, anytime.'],
        ['Seated Ab Vacuum', '0', '0', '20', 'Seated version of stomach vacuum. Pull belly button to spine.'],
        ['Seated Chest Squeeze', '0', '0', '30', 'Press palms together in front of chest. Hold with maximum force.'],
        ['Seated Shoulder Blade Squeeze', '0', '0', '30', 'Pull shoulder blades together and hold. Improves posture.'],
        ['Seated Neck Isometric (Front)', '0', '0', '20', 'Push forehead into hand, resist. Strengthens neck.'],
        ['Seated Neck Isometric (Side)', '0', '0', '20', 'Push side of head into hand, resist. Do both sides.'],
        ['Seated Fist Clench', '0', '0', '30', 'Make tight fists and hold. Builds grip and forearm strength.'],
        ['Seated Forearm Plank (Desk)', '0', '0', '30', 'Lean on desk with forearms, hold plank position.'],
        ['Seated Leg Extension Hold', '0', '0', '30', 'Extend leg straight, hold. Isometric quad strengthening.'],
        ['Seated Ankle Dorsiflexion Hold', '0', '0', '30', 'Pull toes toward shin and hold. Strengthens tibialis anterior.'],
        ['', '', '', '', ''],
        ['# === ISOMETRIC MUSCLE FLEXES ===', '', '', '', ''],
        ['Bicep Isometric Flex', '0', '0', '30', 'Flex biceps as hard as possible and hold. Can do both arms or alternate.'],
        ['Tricep Isometric Flex', '0', '0', '30', 'Extend arms and flex triceps hard. Hold the contraction.'],
        ['Chest Isometric Flex', '0', '0', '30', 'Flex pecs as hard as possible. Imagine bringing arms together.'],
        ['Back Isometric Flex', '0', '0', '30', 'Flex lats and back muscles. Pull shoulder blades together.'],
        ['Shoulder Isometric Flex', '0', '0', '30', 'Flex deltoids. Imagine pushing arms out to sides.'],
        ['Quad Isometric Flex', '0', '0', '30', 'Tighten quads, straighten leg. Can do seated or standing.'],
        ['Hamstring Isometric Flex', '0', '0', '30', 'Flex hamstrings. Imagine pulling heel toward glutes.'],
        ['Glute Isometric Flex', '0', '0', '30', 'Squeeze glutes as hard as possible. Can do anywhere.'],
        ['Calf Isometric Flex', '0', '0', '30', 'Point toes and flex calves. Hold the contraction.'],
        ['Ab Isometric Flex', '0', '0', '30', 'Tighten abs as if bracing for a punch. Hold tension.'],
        ['Forearm Isometric Flex', '0', '0', '30', 'Make fist and flex forearms. Hold maximum tension.'],
        ['', '', '', '', ''],
        ['# === SEATED STRETCHES ===', '', '', '', ''],
        ['Seated Neck Stretch (Side)', '0', '0', '30', 'Tilt head to side, gently pull with hand. Stretch neck muscles.'],
        ['Seated Neck Stretch (Forward)', '0', '0', '30', 'Tuck chin to chest, gently pull head forward. Stretch back of neck.'],
        ['Seated Shoulder Stretch', '0', '0', '30', 'Pull one arm across chest with other hand. Stretch shoulder.'],
        ['Seated Tricep Stretch', '0', '0', '30', 'Reach arm overhead, bend elbow, pull with other hand. Stretch tricep.'],
        ['Seated Wrist Flexor Stretch', '0', '0', '30', 'Extend arm, pull fingers back with other hand. Stretch forearm.'],
        ['Seated Wrist Extensor Stretch', '0', '0', '30', 'Extend arm palm down, pull fingers down. Stretch top of forearm.'],
        ['Seated Spinal Twist', '0', '0', '30', 'Sit tall, twist torso to one side. Hold and breathe. Do both sides.'],
        ['Seated Side Bend', '0', '0', '30', 'Reach arm overhead, bend to side. Stretch obliques and lats.'],
        ['Seated Forward Fold', '0', '0', '30', 'Hinge at hips, reach toward toes. Stretch hamstrings and back.'],
        ['Seated Figure-4 Stretch', '0', '0', '30', 'Cross ankle over knee, lean forward. Stretch glutes and hips.'],
        ['Seated Hip Flexor Stretch', '0', '0', '30', 'Sit at edge of chair, extend one leg back. Stretch hip flexor.'],
        ['Seated Ankle Circles', '0', '10', '0', 'Lift foot, rotate ankle in circles. Improves ankle mobility.'],
        ['Seated Cat-Cow Stretch', '0', '10', '0', 'Arch and round spine while seated. Mobilizes spine.'],
        ['Seated Chest Opener', '0', '0', '30', 'Clasp hands behind back, lift chest. Stretch chest and shoulders.'],
        ['Seated Upper Back Stretch', '0', '0', '30', 'Clasp hands forward, round upper back. Stretch between shoulder blades.'],
        ['Seated Quad Stretch', '0', '0', '30', 'Sitting sideways, bend knee and pull foot toward glutes. Stretch quad.'],
        ['Seated Calf Stretch', '0', '0', '30', 'Extend leg, pull toes toward shin with band or hand. Stretch calf.'],
        ['Seated Hamstring Stretch', '0', '0', '30', 'Extend leg on heel, hinge forward. Stretch hamstring.'],
        ['Seated Shoulder Rolls', '0', '10', '0', 'Roll shoulders backward in circles. Releases shoulder tension.'],
        ['Seated Chin Tucks', '0', '10', '0', 'Pull chin straight back. Improves neck posture and stretches.']
    ];
}
