name: Update Portfolio Index

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update index.html
      run: |
        chmod +x update-index.sh
        ./update-index.sh
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update portfolio index"
          git push
        fi